#!/bin/bash
echo Testing ldpq...
./test_run_real.py ldpq;
echo Testing ezq-sw...
./test_run_real.py ezq-sw;
echo Testing frugal1u-rr...
./test_run_real.py frugal1u-rr;
echo Testing frugal2u-sw...
./test_run_real.py frugal2u-sw;
echo All tests completed.
